// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {RCFileType} {Win32\Debug\Project1_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Win32\Debug\Project1_DRC.res' 'Win32\Debug\Project1_DRC.rc'}

{$E ENU}

begin
end.
